# Generated by Django 5.1.3 on 2024-12-12 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0004_alter_participante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
