# Generated by Django 5.1.4 on 2024-12-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0006_alter_participante_cpf_alter_participante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidade',
            field=models.PositiveIntegerField(),
        ),
    ]
