# Generated by Django 5.1.4 on 2024-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0010_alter_evento_capacidade_alter_evento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
