# Generated by Django 5.1.4 on 2024-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0011_alter_evento_capacidade_alter_evento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
