# Generated by Django 5.1.4 on 2024-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0012_alter_participante_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
